### ISSUE TITLE
[API Detran] Consultar pontos por CPF e CNH direto do banco no Detran

### ISSUE THREAD

**Issue by alvarollmenezes** [prodest/es-na-palma-da-mao-backend#15]

**Comment by maraifernandalv** [comment]
Olá, Álvaro! Você poderia disponibilizar essa API novamente? Faço parte de uma empresa júnior do Movimento Empresa Júnior, a CONSELT, e estamos trabalhando em um projeto de software onde a pessoa procuraria pelo CNH ou CPF e teria os pontos da carteira da pessoa. Poderia disponibilizar?
