### ISSUE TITLE
Sep - Erro ao consultar processo

### ISSUE THREAD

**Issue by hoisel** [prodest/es-na-palma-da-mao-backend#24]
A consultar sep, a api retorna um erro não tratado nos seguintes casos:

1. número do processo maior ou igual a 10 caracteres
2. número do processo contento caracteres não numéricos

**Comment by alvarollmenezes** [comment]
@hoisel  
Será tratado e enviado um erro com status 400 e mensagem de erro para ser exibida ao usuário

**Comment by alvarollmenezes** [comment]
Closed by prodest/api-sep#c2e3b43bfc7fadc842c248bd545f74dd4fb46e15
