### ISSUE TITLE
Erro 400 - invalid_grant

### ISSUE THREAD

**Issue by hoisel** [prodest/es-na-palma-da-mao-backend#28]
Erro 400 não tratado relativo à requisição: https://acessocidadao.es.gov.br/is/connect/token

![image](https://cloud.githubusercontent.com/assets/400244/18711474/85632db0-7fe0-11e6-883f-8b0128d28d5e.png)

![image](https://cloud.githubusercontent.com/assets/400244/18711494/94b744ea-7fe0-11e6-8791-1071de0962cd.png)

**Comment by alvarollmenezes** [comment]
Vamos ver daqui 15 dias, em torno do dia 06/11.
